/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: assetfactory (https://sketchfab.com/assetfactory)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/skateboard-59552a6040fe4f8d8510d3b17ac5abbd
Title: Skateboard
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type Props = {};

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
  };
  materials: {
    skateboard: THREE.MeshStandardMaterial;
  };
};

export function Model(props: Props) {
  const { nodes, materials } = useGLTF(
    "/glb/skateboard.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Skateboardobjcleanermaterialmergergles">
            <mesh
              name="Object_2"
              castShadow
              receiveShadow
              geometry={nodes.Object_2.geometry}
              material={materials.skateboard}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/glb/skateboard.glb");
