/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: James (https://sketchfab.com/james)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/skateboard-c0ace7aac91145e985c473652dcd3a5d
Title: Skateboard
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type Props = {};

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_16: THREE.Mesh;
    Object_19: THREE.Mesh;
    Object_20: THREE.Mesh;
    Object_23: THREE.Mesh;
    Object_24: THREE.Mesh;
    Object_27: THREE.Mesh;
  };
  materials: {
    ["20_-_Default"]: THREE.MeshStandardMaterial;
    SILVER: THREE.MeshStandardMaterial;
    metal_ad_1: THREE.MeshStandardMaterial;
    skateboard: THREE.MeshStandardMaterial;
  };
};

export function Skateboard3D(props: Props) {
  const { nodes, materials } = useGLTF("/skateboard.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="skates3DS">
            <group
              name="wheel_unoS"
              position={[195.901, 1625.898, 70.19]}
              rotation={[Math.PI, -0.007, 1.575]}
              scale={0.316}
            >
              <group
                name="3DSMeshMatrix"
                position={[5152.195, 596.322, 226.891]}
                rotation={[-3.134, 0, 1.575]}
                scale={3.167}
              >
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials["20_-_Default"]}
                />
              </group>
            </group>
            <group
              name="wheelos4os"
              position={[200.362, 761.858, 66.587]}
              rotation={[Math.PI, -0.007, Math.PI / 2]}
              scale={0.316}
            >
              <group
                name="3DSMeshMatrix_1"
                position={[2412.958, 633.009, 215.585]}
                rotation={[-3.134, 0, Math.PI / 2]}
                scale={3.167}
              >
                <mesh
                  name="Object_7"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_7.geometry}
                  material={materials["20_-_Default"]}
                />
              </group>
            </group>
            <group
              name="wh-treisos"
              position={[-160.931, 762.793, 69.286]}
              rotation={[Math.PI, -0.007, Math.PI / 2]}
              scale={0.316}
            >
              <group
                name="3DSMeshMatrix_2"
                position={[2415.919, -511.31, 215.667]}
                rotation={[-3.134, 0, Math.PI / 2]}
                scale={3.167}
              >
                <mesh
                  name="Object_10"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={materials["20_-_Default"]}
                />
              </group>
            </group>
            <group
              name="Object02"
              position={[-26.767, 819.876, 93.519]}
              rotation={[-Math.PI, -0.007, -Math.PI]}
              scale={0.316}
            >
              <group
                name="3DSMeshMatrix_3"
                position={[-86.965, -2596.711, 295.556]}
                rotation={[-Math.PI, 0.007, -Math.PI]}
                scale={3.167}
              >
                <mesh
                  name="Object_13"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_13.geometry}
                  material={materials.SILVER}
                />
              </group>
            </group>
            <group
              name="wheel_Deux"
              position={[-164.875, 1626.19, 72.86]}
              rotation={[Math.PI, -0.007, Math.PI / 2]}
              scale={0.316}
            >
              <group
                name="3DSMeshMatrix_4"
                position={[5150.47, -523.883, 226.891]}
                rotation={[-3.134, 0, Math.PI / 2]}
                scale={3.167}
              >
                <mesh
                  name="Object_16"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_16.geometry}
                  material={materials["20_-_Default"]}
                />
              </group>
            </group>
            <group
              name="trucktwice"
              position={[-14.551, 1561.884, 73.179]}
              rotation={[-Math.PI / 2, 0, -3.134]}
              scale={0.316}
            >
              <group
                name="3DSMeshMatrix_5"
                position={[-47.8, -231.423, -4946.799]}
                rotation={[-Math.PI / 2, 0.007, Math.PI]}
                scale={3.167}
              >
                <mesh
                  name="Object_19"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_19.geometry}
                  material={materials.metal_ad_1}
                />
                <mesh
                  name="Object_20"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_20.geometry}
                  material={materials.metal_ad_1}
                />
              </group>
            </group>
            <group
              name="truck_One"
              position={[0.397, 826.463, 69.729]}
              rotation={[Math.PI / 2, 0, -0.026]}
              scale={0.316}
            >
              <group
                name="3DSMeshMatrix_6"
                position={[4.439, -220.806, 2617.573]}
                rotation={[-Math.PI / 2, -0.026, 0]}
                scale={3.167}
              >
                <mesh
                  name="Object_23"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_23.geometry}
                  material={materials.metal_ad_1}
                />
                <mesh
                  name="Object_24"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_24.geometry}
                  material={materials.metal_ad_1}
                />
              </group>
            </group>
            <group
              name="wood-board"
              position={[-8.311, 1195.471, 172.13]}
              rotation={[-Math.PI / 2, 0, -3.134]}
              scale={0.316}
            >
              <group
                name="3DSMeshMatrix_7"
                position={[-30.354, -544.958, -3786.295]}
                rotation={[-Math.PI / 2, 0.007, -Math.PI]}
                scale={3.167}
              >
                <mesh
                  name="Object_27"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_27.geometry}
                  material={materials.skateboard}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/skateboard.glb");
